baseURL = "https://kmaris.net/"
languageCode = "en-us"
title = "kmaris"
theme = "hugo-xmin"
#footnotereturnlinkcontents = "↩""
#footnotereturnlinkcontents = "↩"

[params]
description = "Personal webspace of Kevin Maris."
footer = "&copy; Kevin Maris 2020 [Github](https://github.com/kmaris) | [Gitlab](https://gitlab.com/kmaris)"

[permalinks]
note = "/note/:year/:month/:day/:slug/"
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[[menu.main]]
name = "CV"
url = "cv/"
weight = 3

[[menu.main]]
name = "Categories"
url = "categories/"
weight = 4

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 5

[[menu.main]]
name = "Subscribe"
url = "index.xml"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "tango"
